import com.google.fhir.model.r4.Resource
import com.google.fhir.model.r4.Boolean
import com.google.fhir.fhirpath.parsers.generated.fhirpathLexer
import com.google.fhir.fhirpath.parsers.generated.fhirpathParser
import com.google.fhir.model.r4.ContactPoint
import com.google.fhir.model.r4.Patient
import org.antlr.v4.kotlinruntime.CharStreams
import org.antlr.v4.kotlinruntime.CommonTokenStream

/**
 * Evaluates a FHIRPath expression against a single FHIR resource.
 *
 * @param expression The FHIRPath string to evaluate (e.g., "Patient.name.given").
 * @param resource The initial FHIR resource to run the expression against.
 * @return A collection of `Base` FHIR elements that result from the evaluation.
 * Non-FHIR results (literals) are filtered out.
 */
fun evaluateFhirPath(expression: String, resource: Resource): Collection<Any> {
    val evaluator = FhirPathEvaluator(initialContext = resource)
    val result = evaluator.visit(
        fhirpathParser(
            CommonTokenStream(
                fhirpathLexer(
                    CharStreams.fromString(
                        expression
                    )
                )
            )
        ).expression()
    )

    return result
}

/**
 * The core of the FHIRPath engine. This class walks the parse tree generated by ANTLR
 * and evaluates the expression. It uses a visitor pattern, with a method for each
 * type of grammar rule.
 *
 * @param initialContext The starting collection of FHIR resources for the expression.
 */
class FhirPathEvaluator(private val initialContext: Resource) :
    com.google.fhir.fhirpath.parsers.generated.fhirpathBaseVisitor<Collection<Any>>() {
    /**
     * The default result for visiting a node. Returns an empty list.
     */
    override fun defaultResult(): Collection<Any> = emptyList()

    /**
     * How to combine results from sibling nodes. We union them together.
     */
    override fun aggregateResult(
        aggregate: Collection<Any>,
        nextResult: Collection<Any>,
    ): Collection<Any> {
        return aggregate + nextResult
    }

    /**
     * Visits an invocation expression (e.g., `... .member` or `... .function()`).
     * This is the correct method for handling the dot operator.
     */
    override fun visitInvocationExpression(ctx: fhirpathParser.InvocationExpressionContext): Collection<Any> {
        // An InvocationExpression is always `expression . invocation`.
        // First, we evaluate the `expression` part on the left.
        val context = visit(ctx.expression())

        // Then, we get the `invocation` child node on the right.
        val invocationNode = ctx.invocation()

        // Correct way: Check the runtime type of the invocationNode.
        return when (invocationNode) {
            is fhirpathParser.MemberInvocationContext -> {
                // Here, invocationNode is smart-cast to MemberInvocationContext.
                val memberName = invocationNode.identifier().text
                context.flatMap { item ->
                    accessField(item, memberName)
                }
            }

            is fhirpathParser.FunctionInvocationContext -> {
                // Here, invocationNode is smart-cast to FunctionInvocationContext.
                val functionNode = invocationNode.function()
                val functionName = functionNode.identifier().text
                val params =
                    functionNode.paramList()?.expression()?.map { visit(it!!) } ?: emptyList()
                // TODO: Implement actual function logic based on functionName and params
                println("Function call to '$functionName' with params: $params. Not yet implemented.")
                emptyList()
            }

            is fhirpathParser.ThisInvocationContext -> {
                // $this simply returns the context it's evaluated on.
                context
            }
            // Add other invocation types like $index, $total here
            else -> emptyList()
        }
    }


    /**
     * Visits an equality expression (e.g., `... = ...` or `... != ...`).
     */
    override fun visitEqualityExpression(ctx: fhirpathParser.EqualityExpressionContext): Collection<Any> {
        // Evaluate the left and right sides of the operator.
        // The expression() accessor returns a list of two elements.
        // We use `!!` because the grammar guarantees these expressions exist.
        val left = visit(ctx.expression(0)!!)
        val right = visit(ctx.expression(1)!!)

        // Per FHIRPath spec, if either side is empty, the result is empty.
        if (left.isEmpty() || right.isEmpty()) {
            return emptyList()
        }

        // Get the operator token text (e.g., '=', '!=', '~').
        val op = ctx.getChild(1)!!.text

        // Per FHIRPath spec, equality is true if any item on the left equals any item on the right.
        var equalityResult = false
        loop@ for (leftItem in left) {
            for (rightItem in right) {
                // NOTE: A full implementation requires a robust comparison function that understands
                // FHIR primitive types (e.g., comparing a FHIR Boolean to a Kotlin Boolean).
                // This is a simplified comparison for demonstration.
                if (compareItems(leftItem, rightItem)) {
                    equalityResult = true
                    break@loop // Found a match, no need to check further.
                }
            }
        }

        // Handle negation for '!=' and '!~' operators.
        val finalResult = when (op) {
            "!=", "!~" -> !equalityResult
            else -> equalityResult
        }

        return listOf(finalResult)
    }

    override fun visitMemberInvocation(ctx: fhirpathParser.MemberInvocationContext): Collection<Any> {
        val identifier = ctx.identifier().text
        return accessField(initialContext, identifier)
    }

    /**
     * Visits a literal (e.g., `'official'`, `true`, `5.0`).
     */
    override fun visitLiteralTerm(ctx: fhirpathParser.LiteralTermContext): Collection<Any> {
        // A LiteralTerm is a wrapper around a single `literal` node.
        val literalNode = ctx.literal()

        // Correct way: Check the runtime type of the literalNode.
        return when (literalNode) {
            is fhirpathParser.StringLiteralContext -> {
                // The raw text includes quotes, so we strip them. e.g., 'official' -> official
                listOf(literalNode.text.drop(1).dropLast(1))
            }

            is fhirpathParser.NumberLiteralContext -> {
                // Use Kotlin's Double as a simplified, dependency-free representation.
                listOf(literalNode.text.toDouble())
            }

            is fhirpathParser.BooleanLiteralContext -> {
                listOf(literalNode.text.toBoolean())
            }

            is fhirpathParser.NullLiteralContext -> {
                // The spec says {} is an empty collection.
                emptyList()
            }
            // TODO: Add support for Date, DateTime, Time, and Quantity literals.
            else -> emptyList()
        }
    }

    /**
     * Visits a parenthesized expression (e.g., `( ... )`).
     */
    override fun visitParenthesizedTerm(ctx: fhirpathParser.ParenthesizedTermContext): Collection<Any> {
        // The result is simply the result of the expression inside the parentheses.
        return visit(ctx.expression())
    }


    /**
     * Helper function to access a field on a FHIR resource using Kotlin reflection.
     * Note: For optimal performance, especially in KMP targets like JS, a
     * descriptor-based approach would be better than reflection.
     */
    private fun accessField(resource: Any, fieldName: String): Collection<Any> {
        return when (resource) {
            is Patient -> {
                when (fieldName) {
                    "name" -> resource.name?.filterNotNull() ?: emptyList()
                    "birthDate" -> resource.birthDate?.let { listOf(it) } ?: emptyList()
                    "telecom" -> resource.telecom?.filterNotNull() ?: emptyList()
                    else -> emptyList()
                }
            }
            is ContactPoint -> {
                when (fieldName) {
                    "system" -> resource.system?.let { listOf(it) } ?: emptyList()
                    "value" -> resource.value?.let { listOf(it) } ?: emptyList()
                    "use" -> resource.use?.let { listOf(it) } ?: emptyList()
                    else -> emptyList()
                }
            }
            else -> return emptyList()
        }
    }

    /**
     * A simplified comparison function. A real implementation needs to be more robust.
     */
    private fun compareItems(left: Any, right: Any): kotlin.Boolean {
        // Unbox FHIR Boolean from the google/kotlin-fhir model to a primitive kotlin.Boolean
        val leftUnboxed = if (left is Boolean) left.value else left
        val rightUnboxed = if (right is Boolean) right.value else right

        if (leftUnboxed is Number && rightUnboxed is Number) {
            return leftUnboxed.toDouble() == rightUnboxed.toDouble()
        }

        return leftUnboxed == rightUnboxed
    }
}