/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.fhir.fhirpath

import com.google.fhir.fhirpath.functions.invoke
import com.google.fhir.fhirpath.members.accessMember
import com.google.fhir.fhirpath.operators.comparison.compare
import com.google.fhir.fhirpath.operators.equality.equality
import com.google.fhir.fhirpath.parsers.generated.fhirpathBaseVisitor
import com.google.fhir.fhirpath.parsers.generated.fhirpathParser
import com.google.fhir.model.r4.FhirDate
import com.google.fhir.model.r4.FhirDateTime
import kotlinx.datetime.LocalTime

/**
 * The core of the FHIRPath engine. This class walks the parse tree generated by ANTLR and evaluates
 * the expression. It uses a visitor pattern, with a method for each type of grammar rule.
 *
 * @param initialContext The starting com.google.fhir.fhirpath.codegen.collection of FHIR resources
 *   for the expression.
 */
internal class FhirPathEvaluator(initialContext: Any) : fhirpathBaseVisitor<Collection<Any>>() {

  private val contextStack = ArrayDeque<Collection<Any>>()

  init {
    contextStack.addLast(listOf(initialContext))
  }

  /** The default result for visiting a node. Returns an empty list. */
  override fun defaultResult(): Collection<Any> = emptyList()

  /** How to combine results from sibling nodes. We union them together. */
  override fun aggregateResult(
    aggregate: Collection<Any>,
    nextResult: Collection<Any>,
  ): Collection<Any> {
    return aggregate + nextResult
  }

  // Expression

  override fun visitInvocationExpression(
    ctx: fhirpathParser.InvocationExpressionContext
  ): Collection<Any> {
    contextStack.addLast(visit(ctx.expression()))
    return visit(ctx.invocation()).also { contextStack.removeLast() }
  }

  override fun visitPolarityExpression(
    ctx: fhirpathParser.PolarityExpressionContext
  ): Collection<Any> {
    val expression = visit(ctx.expression())
    return when (val value = expression.single()) {
      is Int -> listOf(-value)
      is Double -> listOf(-value)
      else -> throw IllegalStateException("Polarity expression cannot be applied to: $value")
    }
  }

  override fun visitInequalityExpression(
    ctx: fhirpathParser.InequalityExpressionContext
  ): Collection<Any> {
    val left = visit(ctx.expression(0)!!)
    val right = visit(ctx.expression(1)!!)

    // Per the spec, inequality operators require both operands to be singletons.
    // If not, the result is an empty collection.
    val leftSingleton = left.singleOrNull() ?: return emptyList()
    val rightSingleton = right.singleOrNull() ?: return emptyList()

    // Get the operator token text ('<', '<=', etc.).
    val op = ctx.getChild(1)!!.text

    // Delegate the actual comparison to a helper function.
    val comparisonResult = compare(leftSingleton, rightSingleton)

    // If the types are not comparable, 'compare' returns null.
    // In this case, the result is an empty collection.
    if (comparisonResult == null) {
      return emptyList()
    }

    // Determine the final boolean result based on the operator.
    val finalResult =
      when (op) {
        "<" -> comparisonResult < 0
        "<=" -> comparisonResult <= 0
        ">" -> comparisonResult > 0
        ">=" -> comparisonResult >= 0
        else -> throw IllegalStateException("Unknown inequality operator: $op")
      }

    return listOf(finalResult)
  }

  override fun visitEqualityExpression(
    ctx: fhirpathParser.EqualityExpressionContext
  ): Collection<Any> {
    val left = visit(ctx.expression(0)!!)
    val right = visit(ctx.expression(1)!!)

    if (left.isEmpty() || right.isEmpty()) {
      return emptyList()
    }

    // Get the operator token text (e.g., '=', '!=', '~').
    val op = ctx.getChild(1)!!.text

    val equality = left.size == right.size && left.zip(right).all { (l, r) -> equality(l, r) }

    // Handle negation for '!=' and '!~' operators.
    val finalResult =
      when (op) {
        "!=",
        "!~" -> !equality
        else -> equality
      }

    return listOf(finalResult)
  }

  // Term

  override fun visitParenthesizedTerm(
    ctx: fhirpathParser.ParenthesizedTermContext
  ): Collection<Any> {
    // The result is simply the result of the expression inside the parentheses.
    return visit(ctx.expression())
  }

  // Literal

  override fun visitBooleanLiteral(ctx: fhirpathParser.BooleanLiteralContext): Collection<Any> {
    return listOf(ctx.text.toBoolean())
  }

  override fun visitStringLiteral(ctx: fhirpathParser.StringLiteralContext): Collection<Any> {
    return listOf(ctx.text.drop(1).dropLast(1))
  }

  override fun visitNumberLiteral(ctx: fhirpathParser.NumberLiteralContext): Collection<Any> {
    val numberText = ctx.text
    return if (numberText.contains('.')) {
      listOf(numberText.toDouble())
    } else {
      listOf(numberText.toInt())
    }
  }

  override fun visitDateLiteral(ctx: fhirpathParser.DateLiteralContext): Collection<Any> {
    val dateText = ctx.text.removePrefix("@")
    return try {
      listOf(FhirDate.Companion.fromString(dateText)!!)
    } catch (_: Exception) {
      emptyList()
    }
  }

  override fun visitDateTimeLiteral(ctx: fhirpathParser.DateTimeLiteralContext): Collection<Any> {
    // Remove suffix "T" for partial DateTime values without the time component
    val dateTimeText = ctx.text.removePrefix("@").removeSuffix("T")
    return try {
      listOf(FhirDateTime.Companion.fromString(dateTimeText)!!)
    } catch (_: Exception) {
      emptyList()
    }
  }

  override fun visitTimeLiteral(ctx: fhirpathParser.TimeLiteralContext): Collection<Any> {
    val timeText = ctx.text.substring(2)

    return try {
      // Use the LocalTime.parse() function from kotlinx-datetime.
      listOf(LocalTime.Companion.parse(timeText))
    } catch (e: Exception) {
      // If the time is not in a valid format, return an empty
      // com.google.fhir.fhirpath.codegen.collection.
      emptyList()
    }
  }

  override fun visitQuantityLiteral(ctx: fhirpathParser.QuantityLiteralContext): Collection<Any> {
    return super.visitQuantityLiteral(ctx)
  }

  // Invocation

  override fun visitMemberInvocation(ctx: fhirpathParser.MemberInvocationContext): Collection<Any> {
    val context = contextStack.last()
    val memberName = visit(ctx.identifier()).first() as String

    val fhirPathType = FhirPathType.fromString(memberName)
    if (fhirPathType != null) {
      return listOf(fhirPathType)
    }

    with(contextStack.first().single()) {
      if (this::class.simpleName == memberName) {
        return listOf(this)
      }
    }

    return context.flatMap { item ->
      val fieldValue = accessMember(item, memberName)
      when (fieldValue) {
        null -> emptyList()
        is List<*> -> fieldValue as Collection<Any>
        else -> listOf(fieldValue)
      }
    }
  }

  override fun visitFunctionInvocation(
    ctx: fhirpathParser.FunctionInvocationContext
  ): Collection<Any> {
    val context = contextStack.last()
    val functionNode = ctx.function()
    val functionName = visit(functionNode.identifier()).first() as String

    return when (functionName) {
      "where" -> {
        val expression = functionNode.paramList()!!.expression().single()
        context.filter {
          // Set the single item in the collection as the context for the expression
          contextStack.addLast(listOf(it))
          val result = visit(expression)
          contextStack.removeLast()
          result.singleOrNull() == true
        }
      }
      "select" -> {
        val projection = functionNode.paramList()!!.expression().single()
        context.flatMap {
          // Set the single item as the context for the projection
          contextStack.addLast(listOf(it))
          val projectionResult = visit(projection)
          contextStack.removeLast()
          projectionResult
        }
      }
      // First-order functions that do not require evaluation of expressions within a context
      else -> {
        val params = functionNode.paramList()?.expression()?.flatMap { visit(it) } ?: emptyList()
        invoke(functionName, context, params)
      }
    }
  }

  override fun visitThisInvocation(ctx: fhirpathParser.ThisInvocationContext): Collection<Any> {
    return contextStack.last()
  }

  // Identifier

  override fun visitIdentifier(ctx: fhirpathParser.IdentifierContext): Collection<Any> {
    val identifierText = ctx.text
    return listOf(identifierText.removeSurrounding("`"))
  }
}
